// REGISTER CONSTANTS
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// LOGIN CONSTANTS
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GET_USER_VERIFIED = "GET_USER_VERIFIED";
export const SET_USER_VERIFIED = "SET_USER_VERIFIED";

// LOGOUT CONSTANTS
export const USER_SIGN_OUT = "USER_SIGN_OUT";
